### ISSUE TITLE
App is crashing!

### ISSUE THREAD

**Issue by yasirtahir** [alhazmy13/HijriDatePicker#10]
Dear,

If you click on the empty area where there is no date, the application got crashed with an error Unable to parse Integer. Following is the code line of HijriCalendarView class where application is crashing:

calendarInstance.setDay(Integer.parseInt(temp.getText().toString()));

To fix this issues, correct the String empty check:

if (!temp.getText().toString().isEmpty())
to
if (!temp.getText().toString().trim().isEmpty())

**Comment by alhazmy13** [comment]
Solved Now
