### ISSUE TITLE
Button colors issue

### ISSUE THREAD

**Issue by yasirtahir** [alhazmy13/HijriDatePicker#11]
Dear,

Below image is taken from a device running on 5.0 OS. The button colors are not changing to Blue as you can see in the image. Although, I override the color property in my app but that is not affected to buttons at all.

![5 0](https://cloud.githubusercontent.com/assets/15076018/13737512/061ae590-e9cf-11e5-860c-4009e67c58ba.PNG)

Similarly, on lower device running on 4.2.2 OS, the button color is white irrespective of the theme color.

![4 2 2](https://cloud.githubusercontent.com/assets/15076018/13737571/5b8369d0-e9cf-11e5-854a-852515c52ba5.PNG)

**Comment by alhazmy13** [comment]
It has been solved with version 1.3.5, please update it from your dependence

**Comment by yasirtahir** [comment]
I am using version 1.3.5.

![capture](https://cloud.githubusercontent.com/assets/15076018/13777720/cbc3e91a-eac2-11e5-9f77-97f20a334f75.PNG)
