### ISSUE TITLE
مشكلة في تغيير التاريخ الهجري بشهر ذي الحجة | Issue in Hijri Date Accuracy

### ISSUE THREAD

**Issue by Loai-Alhalabi** [alhazmy13/HijriDatePicker#12]
السلام عليكم ورحمة الله وبركاته ...

هل سيتم تحديث مكتبة الـ HijriDatePicker , لأنه كما تعلم تم تغيير الروزنامة حالياً بأول شهر ذي الحجة 

الرجاء النظر بهذه المشكلة وأشكرك جداً , وأنا من مستخدمين هذه المكتبة شخصياً , جزاك الله خيراً عليها.

كما أتمنى أن يكون بها إضافات أخرى قد تساعد على إستخدامها بشكل أكبر وأوسع .

**Comment by alhazmy13** [comment]
وعليكم السلام, ساقوم بتعديلها وساضيف خيار للمطور لزيادة يوم او انقاصه من نفس كلاس الـ Build 
اذا عندك اي اقتراحات اكون شاكر لك

**Comment by Loai-Alhalabi** [comment]
as the Library Contains : MaxYear , MinYear
it should have 
MinMonth, MaxMonth

**Comment by mohamedma872** [comment]
> السلام عليكم ورحمة الله وبركاته ...
> 
> هل سيتم تحديث مكتبة الـ HijriDatePicker , لأنه كما تعلم تم تغيير الروزنامة حالياً بأول شهر ذي الحجة
> 
> الرجاء النظر بهذه المشكلة وأشكرك جداً , وأنا من مستخدمين هذه المكتبة شخصياً , جزاك الله خيراً عليها.
> 
> كما أتمنى أن يكون بها إضافات أخرى قد تساعد على إستخدامها بشكل أكبر وأوسع .

https://github.com/mohamedma872/HijriDatePickerPlus

**Comment by mohamedma872** [comment]
> as the Library Contains : MaxYear , MinYear it should have MinMonth, MaxMonth

https://github.com/mohamedma872/HijriDatePickerPlus
