### ISSUE TITLE
Failed to resolve: net.alhazmy13.hijridatepicker:library:2.0.0

### ISSUE THREAD

**Issue by shafqatjamil** [alhazmy13/HijriDatePicker#19]
I also tried using maven but still not able to add library

**Comment by alhazmy13** [comment]
Hi @shafqatjamil 
Can you add below code to your `build.gradle` , it's should be fixed with two days 
```
allprojects {
    repositories {
        maven { url 'https://dl.bintray.com/alhazmy13/maven/' }
    }
}
```

let me know if it works or not.

**Comment by alhazmy13** [comment]
it should be work fine without above lines.
