### ISSUE TITLE
Choose the ui language

### ISSUE THREAD

**Issue by iturki** [alhazmy13/HijriDatePicker#2]
Salam,
Good work Abdullah!
 It seems that there is no way to choose the language of the ui (i.e. done button, cancel button, month name, ...). It would be nice if the language can be set like this:

```
dialog.setUILanguage(HijriCalendarDialog.ARABIC);
```

**Comment by alhazmy13** [comment]
Salam,
It will be inshAllah in next update with another features, and please let me know if you have any suggestions for improving the library

Regards,,

**Comment by vzool** [comment]
Salam @alhazmy13 ,

Any update about this feature?

Thanks
