### ISSUE TITLE
Save value to preference

### ISSUE THREAD

**Issue by creativetrendsapps** [alhazmy13/HijriDatePicker#21]
With this library how would I go about putting the selected time value within my preferences? Like the AM value and PM value?

**Comment by alhazmy13** [comment]
Hi @creativetrendsapps 

Each dialog has an own listener, you can read the values from it, for example, the date dialog it will back to you these values (year, month, day) or for the time dialog (hour, minute and second).

You can save it to your preface like any normal value.
 
```java
pre.putInt("hour",hour);
```
At any time you can read the values from shared preference and pass it to your dialog instance.
