### ISSUE TITLE
About Hijri calendar

### ISSUE THREAD

**Issue by mohe01** [alhazmy13/HijriDatePicker#22]
it display a month in hijri with 31 days .... so how can modify to display just 30 day and is there and code to add or minus 2 days

**Comment by alhazmy13** [comment]
Hi @mohe01, in which month exactly you received 31 days?

**Comment by mohe01** [comment]
example when i start the app in this month augest i  receive dhu alqidaa 31 days

**Comment by alhazmy13** [comment]
It should be fixed with version `2.0.1`
