### ISSUE TITLE
تحويل الواجهة إلى اللغة العربية | Arabic UI

### ISSUE THREAD

**Issue by vzool** [alhazmy13/HijriDatePicker#25]
السلام عليكم ،،،

 أشكرك على هذا المجهود الجميل في إخراج هذه المكتبة بهذا الشكل ، ولكني لم أجد طريقة لتحويل النصوص إلى اللغة العربية مثل أسماء التواريخ  والشهور ، هي الأرقام بالعربي صحيح وليست بالهندي بس الكلمات باللغة الإنكليزية.

أنا بحثت عن حلول ولكن لم تنجح معاي للأسف
```java
Calendar uCal = new UmmalquraCalendar(1433, UmmalquraCalendar.RABI_AWWAL, 8, 20, 45, 10);
SimpleDateFormat dateFormat = new SimpleDateFormat("", new Locale("ar"));
dateFormat.setCalendar(uCal);
```

هل عندك فكرة تضيف دعم للغة العربية؟

شكرا جزيلا لك

#2

**Comment by Amr-Elmadah** [comment]
Here's a forked repository provides what you require till alhamzy make pull request to merge the 2 repositories if he wants
https://github.com/Amr-Elmadah/HijriDatePicker

**Comment by alhazmy13** [comment]
Thanks @Amr-Elmadah 
This is a PR from your fork
https://github.com/alhazmy13/HijriDatePicker/pull/33

**Comment by alhazmy13** [comment]
Fixed with version [2.1.0](https://github.com/alhazmy13/HijriDatePicker/releases/tag/2.1.0)
