### ISSUE TITLE
Hijri Date Limitation to 1400 AH

### ISSUE THREAD

**Issue by vzool** [alhazmy13/HijriDatePicker#27]
Salam,

I noticed that the minimum year for Hijri date is 1400 AH, can I increase this limitation?

Thanks

**Comment by alhazmy13** [comment]
Fixed with version [2.1.0](https://github.com/alhazmy13/HijriDatePicker/releases/tag/2.1.0)

**Comment by noura-rizk** [comment]
Hi, could you please tell me how to set min date less than 1400? Thanks in advance
