### ISSUE TITLE
مشكلة في swipe 

### ISSUE THREAD

**Issue by mohshaat1990** [alhazmy13/HijriDatePicker#3]
مشكلة في swipe ي
يمين وشمال عند الأيام
ساعات بتشتغل وساعات لا

**Comment by alhazmy13** [comment]
جاري العمل عليها,,

**Comment by mohshaat1990** [comment]
مشكلة في رقم الشهر واسم الشهر  
الحل
 public int getMonth(){
        return countMonth+1;
    }
    public String getMonthName(){
        return monthNames[countMonth];
    }
