### ISSUE TITLE
Enable set locale method to be able to change localization of library

### ISSUE THREAD

**Issue by Amr-Elmadah** [alhazmy13/HijriDatePicker#32]
to be able to pass the required locale to the library and then make it work with the required language like Arabic especially

**Comment by Amr-Elmadah** [comment]
I've forked your repository and worked on it to make it provide set localization, you can make pull request now to merge

**Comment by alhazmy13** [comment]
Done With https://github.com/alhazmy13/HijriDatePicker/pull/33
Thank You @Amr-Elmadah

**Comment by alhazmy13** [comment]
Fixed with version [2.1.0](https://github.com/alhazmy13/HijriDatePicker/releases/tag/2.1.0)
