### ISSUE TITLE
UmmalquraCalendar is missing

### ISSUE THREAD

**Issue by Amrhalawani** [alhazmy13/HijriDatePicker#39]
Hi,

the library didn't include UmmalquraCalendar class on 2.1.0 version

**Comment by abhimaanmadhav** [comment]
solved in this pull request.
https://github.com/alhazmy13/HijriDatePicker/pull/40/files.

awaiting a lib release

**Comment by alhazmy13** [comment]
Fixed

**Comment by iAhmedAwad** [comment]
Hello, same issue!
Library doesn't include UmmalquraCalendar class!
