### ISSUE TITLE
Can I use Hijri DatePicker as Spinner Mode and use it inside xml file ?

### ISSUE THREAD

**Issue by Al-Hussein-96** [alhazmy13/HijriDatePicker#41]
مرحباً
هل استطيع استخدام التاريخ الهجري كما في الصورة ؟
وبدون عرضها كـ dialog
![image](https://user-images.githubusercontent.com/31496257/87409155-3bc5ae80-c5cd-11ea-838d-0e62ba61b7a1.png)

**Comment by Al-Hussein-96** [comment]
@alhazmy13

**Comment by alhazmy13** [comment]
اهلا, تقدر تبنيها عن طريق مكتبه ام القرى بواجهة مخصصة, المكتبة الحالية لا تدعم التصميم المرفق
