### ISSUE TITLE
Not able to move past Islamic year 1400 in the date picker dialog.

### ISSUE THREAD

**Issue by codingtosurvive** [alhazmy13/HijriDatePicker#45]
Hi, 

I have been trying to put a hijri date picker dialog to fetch date of birth. But it won't go past year 1400 Islamic year. Please help.

calmin.add(Calendar.YEAR,-80);
                        mindate = calmin.getTimeInMillis();
                        maxdate = calmax.getTimeInMillis();
                        showDatePicker(view, mindate, maxdate, tiDob.getTag());

HijriDatePickerDialog dpd = HijriDatePickerDialog.newInstance(
                hijriDateSetListener,
                now.get(Calendar.YEAR),
                now.get(Calendar.MONTH),
                now.get(Calendar.DAY_OF_MONTH)
        );
        dpd.setThemeDark(false);
        dpd.vibrate(false);
        dpd.dismissOnPause(true);
        dpd.showYearPickerFirst(false);
        dpd.setVersion(HijriDatePickerDialog.Version.VERSION_2);

        if(minDate!=0) {
            UmmalquraCalendar calMinDate = new UmmalquraCalendar();
            calMinDate.setTimeInMillis(minDate);
            dpd.setMinDate(calMinDate);
        }

        if(maxDate!=0) {
            UmmalquraCalendar calMaxDate = new UmmalquraCalendar();
            calMaxDate.setTimeInMillis(maxDate);
            dpd.setMaxDate(calMaxDate);
        }

**Comment by ijoshivaibhav** [comment]
hey ..any solution???

**Comment by codingtosurvive** [comment]
Hi, Use ummalqura-calendar 2.0.0
