### ISSUE TITLE
Incorrect parsing 

### ISSUE THREAD

**Issue by anastr** [alhazmy13/HijriDatePicker#46]
I have this code:
```kotlin
val dateFormat = SimpleDateFormat("dd/MM/yyyy", Locale.US)
dateFormat.calendar = UmmalquraCalendar()

val calendar = UmmalquraCalendar()
calendar.time = dateFormat.parse("30/02/1442")!!  // This will result calendar dated "01/02/1442" !

assert(dateFormat.format(calendar.time) == "30/02/1442")  //  Wrong!
```
This happen only when `dd` is `30`.
It seems every time the day was `30` its parsing always `01`.

What I'm trying to do is parsing `String` date to `Calendar` object to pass it to `HijriDatePickerDialog`.

**Comment by anastr** [comment]
moved to [ummalqura-calendar issue](https://github.com/msarhan/ummalqura-calendar/issues/26)

**Comment by Sabboo** [comment]
@anastr  Why this issue been moved to the other repository?
I think its related to this one.
I am facing the same issue and the stacktrace point to the HijriDatePickerDialog
