### ISSUE TITLE
gradle implementation problem

### ISSUE THREAD

**Issue by BassamAlim** [alhazmy13/HijriDatePicker#55]
when trying to use the library i get: "Could not find 'net.alhazmy13.hijridatepicker:library:3.0.0'"

**Comment by atifaziz1** [comment]
@BassamAlim You need to add below lines in gradle 

`allprojects {
  repositories {
    jcenter()
    google()
    maven { url "https://dl.bintray.com/alhazmy13/maven" }
  }
}`

**Comment by BassamAlim** [comment]
@atifaziz1 thank you
