### ISSUE TITLE
Button colors not visible when used as a library

### ISSUE THREAD

**Issue by arshad115** [alhazmy13/HijriDatePicker#7]
![device-2016-02-19-145329](https://cloud.githubusercontent.com/assets/963798/13172349/75c97bcc-d719-11e5-9784-c7c5f9c6a51f.png)

Button colors not visible when used as a library. I have added <color name="hijri_date_picker_accent_color">#009688</color> in the values.

**Comment by alhazmy13** [comment]
Make sure to override 
`<color name="hijri_date_picker_accent_color">#FF9688</color>
`

<img width="314" alt="screen shot 2016-02-21 at 12 11 57 pm" src="https://cloud.githubusercontent.com/assets/4659608/13201881/15d7f234-d895-11e5-8e6a-6a1a84af9efc.png">

**Comment by arshad115** [comment]
I am still getting white boxes instead of buttons. I have the property <color name="hijri_date_picker_accent_color">#FF9688</color> overridden in my app. 
![device-2016-02-26-040912](https://cloud.githubusercontent.com/assets/963798/13337733/f249923e-dc3e-11e5-93d1-4a26915ab0dc.png)

Upon investigating, I found that you have used android:backgroundTint property on the dialog's buttons. android:backgroundTint isn't backwards compatible (API 21 only) and its giving InflateException for the AlertDialog Buttons. Please check it.

**Comment by alhazmy13** [comment]
You right :100: 
It's solved with Version `1.3.5`

**Comment by arshad115** [comment]
Thank you. Good job

**Comment by yasirtahir** [comment]
I am facing the same issue in 1.3.5
